spring:
  application:
    name: ufu

  datasource:
    url: jdbc:mysql://localhost:3306/ufu_db
    username: root
    password: iokshoimong1!M
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080